### PR TITLE
minor grammar and spelling fixes

### PR DESCRIPTION
**Pull request by realytcracker**
performed some minor changes to the language.

### CODE REVIEW

**Comment by caiiiycuk** [comment]
Thank you very much for the fixes. Can you solve style issue?

**Comment by realytcracker** [comment]
hey @caiiiycuk, no problem. which style issue are you referring to?

**Comment by realytcracker** [comment]
nevermind, i see what you meant. fixed!

**Comment by caiiiycuk** [comment]
Thank you!

**Pull request merged**
